# This is a basic workflow to help you get started with Actions

name: Ubuntu Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    environment: build

    defaults:
      run:
        working-directory: packer

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # fix backwards incompatibilities in template
      # - name: Fix Template
      #   uses: hashicorp/packer-github-actions@master
      #   with:
      #     command: fix

      # validate templates
      - run: echo $PWD
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/.

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: packer/.
        env:
          PACKER_LOG: 0
          PKR_VAR_client_id: ${{ secrets.PKR_VAR_CLIENT_ID }} 
          PKR_VAR_client_secret: ${{ secrets.PKR_VAR_CLIENT_SECRET }} 
          PKR_VAR_subscription_id: ${{ secrets.PKR_VAR_SUBSCRIPTION_ID }} 
          PKR_VAR_tenant_id: ${{ secrets.PKR_VAR_TENANT_ID }} 